server:
  port: 8080

spring:
  datasource:
    url: jdbc:h2:mem:hackaton
    driverClassName: org.h2.Driver

  liquibase:
    enabled: true
    change-log: classpath:/db.changelog/db.changelog-master.xml
  h2:
    console:
      enabled: true

  jpa:
    generate-ddl: false
    defer-datasource-initialization: false
    hibernate:
      ddl-auto: none

    show-sql: true
